### ISSUE TITLE
Feature request: Passing ds attributes to nxs attributes

### ISSUE THREAD

**Issue by Pepe-Marquez** [rescipy-project/nxarray#2]
It would be fantastic if the ds.attributes like ['units'] would be carried over in the conversion to .nxs. Would it be possible to implement that? Thanks a lot! 

It is a great package!

**Comment by mpanighel** [comment]
I am really glad the package is useful!

Concerning the propagation of attributes, currently both Dataset and DataArray attributes are carried over when saving into NeXus and when loading back. This is shown in this simple script:

``` python
import nxarray

from nexusformat import nexus
import xarray as xr
import numpy as np

# Create Dataset with attributes and save it to NeXus file
ds = xr.Dataset(attrs={'units': 'm'})
data = xr.DataArray(np.random.randn(2, 3),
                    dims=('x', 'y'),
                    coords={'x': [10, 20], 'y': [1,2,3]},
                    attrs={'dataAttribute': 42},
                    name='some_data')
ds['MyData'] = data
ds.nxr.save('file')

# Show NeXus file tree
ds2 = nexus.nxload('file.nxs')
print(ds2.tree)

# Load NeXus back into Dataset
ds3 = nxarray.load("file.nxs")
ds3
```

Is this what you had in mind? Otherwise please feel free to provide an example for your use case!

**Comment by mpanighel** [comment]
@Pepe-Marquez is the snippet above solving your request or would it be something different? If that is what you had in mind I will close the issue, otherwise feel free to provide an example for your request.

**Comment by Pepe-Marquez** [comment]
Hi Mirco, thanks for this. Yes please, close the issue and I will get back and reopen it shall we find problems in the near future. Thanks a lot!
